function setupBuild()
%% Makefile configuration for standalone build
% Copyright 2022-2023 The MathWorks, Inc.

%% Compiler Setup
selectedCompilerWin="MSVCPP";
% selectedCompilerWin="MINGW";

% Linux uses gcc for build

%% Open MEX Configuration file
mlRoot = getUnixPath(matlabroot);
fileID = fopen(fullfile(computer('arch') +".mk"),'w');

%% MEX Build Information
fprintf(fileID, "#Autogenerated from MATLAB\n");
fprintf(fileID, "SET_ARCH=%s\n", computer('arch'));
fprintf(fileID, "SET_ML_ROOT=%s\n", mlRoot);
if ispc
    fprintf(fileID, "WIN_COMPILER=%s\n", selectedCompilerWin);
    fprintf(fileID, "SET_GLFW_INC_PATH=-I%s\n", getUnixPath( getpref('mujoco', 'glfwIncPath')));
    fprintf(fileID, "SET_GLFW_IMPORTLIB_PATH=%s\n", getUnixPath( getpref('mujoco', 'glfwImportLibPath')) );
else
    fprintf(fileID, "SET_GLFW_INC_PATH=-I/usr/local/include\n");
end
disp('compiler selection and GLFW inc/import path setup done')
mjLibName = "mujoco";
fprintf(fileID, "MJ_LIB_NAME=%s\n", mjLibName);
fprintf(fileID, "SET_MJ_PATH=../lib/%s/%s\n", computer('arch'), mjLibName);

%% MEX Setup Configuration
% This information is not needed when ">>mex -setup c++" is manually called in MATLAB
% Command Window before calling "gmake build"
if ispc
    if selectedCompilerWin=="MSVCPP"
        compilerXML = "msvcpp2022.xml";
    elseif selectedCompilerWin=="MINGW"
        compilerXML = "mingw64_g++_sdk10+.xml";
    end
    fprintf(fileID, 'SET_MEX_SETUP="%s/bin/mex.bat" -setup:"%s/%s/%s"\n', mlRoot, mlRoot, "bin/win64/mexopts", compilerXML);
else
    fprintf(fileID, "SET_MEX_SETUP=mex -setup c++\n");
end

%% Close file
fclose(fileID);

%% Helpers
    function unixPath = getUnixPath(winPath)
        if ispc
            % Using unix path even in windows
            unixPath = join(split(winPath, '\'), '/');
            unixPath = unixPath{:};
        else
            unixPath = winPath;
        end
    end
end